authentication/urls.py
# pylint: disable=C0103
"""Authentication urls module.
"""
from django.urls import path

from authentication.views.delete_custom_user_view import DeleteCustomUserView
from authentication.views.login_view import LoginView
from authentication.views.logout_view import LogoutView
from authentication.views.create_custom_user_view import CreateCustomUserView
from authentication.views.update_custom_user_view import UpdateCustomUserView
from authentication.views.read_custom_user_view import ReadCustomUserView

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'create_custom_user/',
        CreateCustomUserView.as_view(),
        name='create_custom_user'
    ),
    path(
        'delete_custom_user/',
        DeleteCustomUserView.as_view(),
        name='delete_custom_user'
    ),
    path(
        'update_custom_user/',
        UpdateCustomUserView.as_view(),
        name='update_custom_user'
    ),
    path(
        'read_custom_user/',
        ReadCustomUserView.as_view(),
        name='read_custom_user'
    ),
]

chat/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from chat.views.collectivity_discussions_view import (
    CollectivityDiscussionsView
)
from chat.views.create_comment_view import CreateCommentView
from chat.views.create_discussion_view import CreateDiscussionView
from chat.views.read_discussion_view import ReadDiscussionView


app_name = 'chat'

urlpatterns = [
    path(
        'collectivity_discussions/',
        CollectivityDiscussionsView.as_view(),
        name='collectivity_discussions'
    ),
    path(
        'create_comment/<int:id_discussion>/',
        CreateCommentView.as_view(),
        name='create_comment'
    ),
    path(
        'create_discussion/',
        CreateDiscussionView.as_view(),
        name='create_discussion'
    ),
    path(
        'read_discussion/<int:id_discussion>/',
        ReadDiscussionView.as_view(),
        name='read_discussion'
    )
]

information/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from information.views.about_view import AboutView
from information.views.contact_view import ContactView
from information.views.collectivity_dashboard_view import (
    CollectivityDashboardView
)
from information.views.faq_view import FaqView
from information.views.legal_view import LegalView
from information.views.home_view import HomeView

app_name = 'information'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('faq/', FaqView.as_view(), name='faq'),
    path(
        'information/collectivity_dashboard/',
        CollectivityDashboardView.as_view(),
        name='collectivity_dashboard'
    ),
    path('legal/', LegalView.as_view(), name='legal'),
]

authentication/models.py
"""CustomUser model module.
"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from authentication.management.engine.custom_user_manager import (
    CustomUserManager
)
from collectivity.models import Collectivity


class CustomUser(AbstractUser):
    """CustomUser model class. It sa an abstarct of django user class which
    provides all user authentication, login, etc. methods. Implemented in
    order to have email as identifier instead of username provided by default
    by django framework.
    """
    username = None
    email = models.EmailField(_('email address'), max_length=128, unique=True)
    user_name = models.TextField(_('username'), max_length=64, null=False)
    balance = models.BigIntegerField(default=0)
    collectivity = models.ForeignKey(
        Collectivity, on_delete=models.CASCADE, null=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

authentication/forms/create_custom_user_form.py
# pylint: disable=R0903,R0801
"""CreateCustomUserForm module.
"""
from django import forms
from django.contrib.auth.forms import UserCreationForm

from authentication.models import CustomUser


class CreateCustomUserForm(UserCreationForm):
    """CreateCustomUserForm module.
    """

    email = forms.CharField(
        label="Email (identifiant)",
        max_length=128,
        widget=forms.EmailInput(
            attrs={
                'autofocus': True,
                'class': 'form-control form-control-sm',
                'id': 'input_custom_user_email',
            }
        )
    )
    user_name = forms.CharField(
        label="Nom d'utilisateur.rice (visible dans l'app)",
        max_length=64,
        widget=forms.TextInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_custom_user_user_name'
            }
        )
    )
    password1 = forms.CharField(
        label="Mot de passe",
        max_length=32,
        widget=forms.PasswordInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_custom_user_password1'
            }
        )
    )
    password2 = forms.CharField(
        label="Confirmer le mot de passe",
        max_length=32,
        widget=forms.PasswordInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_custom_user_password2'
            }
        )
    )
    postal_code = forms.CharField(
        label='Code postal',
        max_length=5,
        min_length=5,
        widget=forms.TextInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_postal_code',
            },
        )
    )
    collectivity = forms.CharField(
        label='Ville',
        max_length=256,
        widget=forms.TextInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_custom_user_collectivity',
            },
        )
    )
    field_order = [
        'email', 'password1', 'password2', 'user_name', 'postal_code',
        'collectivity'
    ]

    class Meta:
        """ModelForm "inner" metadata class.
        """
        model = CustomUser
        fields = [
            'email', 'user_name', 'password1', 'password2',
        ]

authentication/forms/login_form.py
"""LoginForm module.
"""
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class LoginForm(AuthenticationForm):
    """LoginForm class.
    """

    username = forms.CharField(
        label="Email",
        max_length=128,
        widget=forms.EmailInput(
            attrs={
                'autofocus': True,
                'class': 'form-control form-control-sm',
                'id': 'input_login_email',
            }
        )
    )
    password = forms.CharField(
        label="Mot de passe",
        max_length=32,
        widget=forms.PasswordInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'input_login_password'
            }
        )
    )

authentication/forms/update_custom_user_form.py
# pylint: disable=R0903,R0801
"""UpdateCustomUserForm module.
"""
from django import forms

from authentication.models import CustomUser


class UpdateCustomUserForm(forms.ModelForm):
    """UpdateCustomUserForm class.
    """

    user_name = forms.CharField(
        label="Nom d'utilisateur.rice",
        max_length=64,
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'class': 'form-control form-control-sm',
                'id': 'ecuf_input_user_name'
            }
        )
    )
    postal_code = forms.CharField(
        label='Code postal',
        max_length=5,
        min_length=5,
        widget=forms.TextInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'ecuf_input_postal_code',
            },
        )
    )
    collectivity = forms.CharField(
        label='Ville',
        max_length=256,
        widget=forms.TextInput(
            attrs={
                'autofocus': False,
                'class': 'form-control form-control-sm',
                'id': 'ecuf_input_collectivity',
            },
        )
    )
    field_order = ['user_name', 'postal_code', 'collectivity']

    class Meta:
        """Meta model gives CustomUser "params" to CreateCustomUser class.
        """

        model = CustomUser
        fields = ['user_name']

authentication/views/create_custom_user_view.py
"""CreateCustomUserview module.
"""
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View

from authentication.forms.create_custom_user_form import CreateCustomUserForm
from authentication.management.engine.manager import Manager


class CreateCustomUserView(View):
    """CreateCustomUserview class.
    """

    def __init__(self):
        super().__init__()
        self.manager = Manager()
        self.context = {
            'form': CreateCustomUserForm(),
        }
        self.view_template = 'authentication/create_custom_user.html'
        self.post_view_name = 'authentication:login'

    def get(self, request):
        """CreateCustomUserview view method on client get request.
        """
        return render(request, self.view_template, self.context)

    def post(self, request):
        """CreateCustomUserview method on client post request.
        """
        form = CreateCustomUserForm(request.POST)
        if form.is_valid():
            collectivity = Manager().check_collectivity(
                form.cleaned_data['postal_code'],
                form.cleaned_data['collectivity']
            )
            if collectivity:
                self.manager.create_custom_user(form, collectivity)
                self.manager.activate_collectivity(collectivity)
                messages.add_message(
                    request, messages.SUCCESS, "Création de compte réussie"
                )
                return redirect(self.post_view_name)
            messages.add_message(
                request, messages.ERROR, "Code postal != Ville",
            )
            return render(
                request, self.view_template, {'form': form}
            )
        return render(
            request, self.view_template, {'form': form}
        )

authentication/views/delete_custom_user_view.py
"""DeleteCustomUserview module.
"""
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import render, redirect

from authentication.models import CustomUser
from authentication.views.generic_authentication_view import (
    GenericAuthenticationView
)


class DeleteCustomUserView(GenericAuthenticationView):
    """DeleteCustomUserview class.
    """

    def __init__(self):
        super().__init__()
        self.context = {}
        self.view_template = 'authentication/delete_custom_user.html'
        self.alternative_view_name = 'information:home'

    def get(self, request):
        """DeleteCustomUserview method on client get request.
        """
        return render(request, self.view_template, self.context)

    def post(self, request):
        """DeleteCustomUserview method on client post request.
        """
        custom_user = CustomUser.objects.get(pk=request.user.id)
        custom_user.delete()
        messages.add_message(
            request, messages.SUCCESS, "Suppression de compte réussie"
        )
        logout(request)
        return redirect(self.alternative_view_name)

authentication/views/generic_authentication_view.py
"""GenericAuthenticationView module.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from authentication.management.engine.manager import Manager


class GenericAuthenticationView(LoginRequiredMixin, View):
    """GenericAuthenticationView class.
    """

    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()

authentication/views/login_view.py
"""LoginView module.
"""
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View

from authentication.forms.login_form import LoginForm


class LoginView(View):
    """LoginView class.
    """

    def __init__(self):
        super().__init__()
        self.context = {
            'form': LoginForm(),
        }
        self.view_template = 'authentication/login.html'
        self.post_view_name = 'information:home'

    def get(self, request):
        """LoginView method on client get request.
        """
        return render(request, self.view_template, self.context)

    def post(self, request):
        """LoginView method on client post request.
        """
        logout(request)
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(
                email=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                messages.add_message(
                    request, messages.SUCCESS, "Authentification réussie",
                )
                return redirect(self.post_view_name)
        return render(request, self.view_template, {'form': form})

authentication/views/logout_view.py
"""LogoutView module.
"""
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect

from authentication.views.generic_authentication_view import (
    GenericAuthenticationView
)


class LogoutView(GenericAuthenticationView):
    """LogoutView class.
    """

    def __init__(self):
        super().__init__()
        self.view_name = 'information:home'

    def get(self, request):
        """LogoutView method on client get request.
        """
        logout(request)
        messages.add_message(
            request, messages.SUCCESS, "Déconnexion réussie",
        )
        return redirect(self.view_name)

authentication/views/read_custom_user_view.py
"""ReadCustomUserview module.
"""
# from django.contrib import messages
from django.shortcuts import render
# from django.views import View
from authentication.views.generic_authentication_view import (
    GenericAuthenticationView
)


class ReadCustomUserView(GenericAuthenticationView):
    """ReadCustomUserview class.
    """

    def __init__(self):
        super().__init__()
        self.context = {}
        self.view_template = 'authentication/read_custom_user.html'

    def get(self, request):
        """ReadCustomUserview method on client get request.
        """
        return render(request, self.view_template, self.context)

authentication/views/update_custom_user_view.py
"""UpdateCustomUserview module.
"""
from django.contrib import messages
from django.shortcuts import render, redirect

from authentication.forms.update_custom_user_form import UpdateCustomUserForm
from authentication.models import CustomUser
from authentication.views.generic_authentication_view import (
    GenericAuthenticationView
)


class UpdateCustomUserView(GenericAuthenticationView):
    """UpdateCustomUserview class.
    """

    def __init__(self):
        super().__init__()
        self.context = {
            'form': UpdateCustomUserForm(),
        }
        self.view_template = 'authentication/update_custom_user.html'
        self.alternative_view_name = 'information:home'

    def get(self, request):
        """UpdateCustomUserview method on client get request.
        """
        custom_user = CustomUser.objects.get(pk=request.user.id)
        form = UpdateCustomUserForm(
            initial={
                'user_name': custom_user.user_name,
                'postal_code': custom_user.collectivity.postal_code,
                'collectivity': custom_user.collectivity.name
            }
        )
        self.context['form'] = form
        return render(request, self.view_template, self.context)

    def post(self, request):
        """UpdateCustomUserview method on client post request.
        """
        form = UpdateCustomUserForm(request.POST)
        if form.is_valid():
            collectivity = self.manager.check_collectivity(
                form.cleaned_data['postal_code'],
                form.cleaned_data['collectivity']
            )
            if collectivity:
                self.manager.update_custom_user(request, form, collectivity)
                self.manager.activate_collectivity(collectivity)
                messages.add_message(
                    request, messages.SUCCESS, "Mise à jours réussie",
                )
                return redirect(self.alternative_view_name)
            messages.add_message(
                request, messages.ERROR, "Code postal != Ville",
            )
            return render(request, self.view_template, {'form': form})
        return render(
            request, self.view_template, {'form': form}
        )

authentication/templates/authentication/create_custom_user.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="{% url 'information:home'%}"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Créer un compte</p>
                <form id="create_user_form" action="{% url 'authentication:create_custom_user'%}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group mb-3">
                            {{ field.label }}
                            {{ field }}
                            {% for error in field.errors %}
                                {% if error %}
                                    <p class="text-danger"> {{ error }}</p>
                                {% endif %}
                            {% endfor %}
                            {% if field == form.postal_code or field == form.collectivity%}
                                {% if messages %}
                                    {% for message in messages %}
                                        <p class="text-danger"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endfor %}         
                    <button type="submit" class="btn btn-primary btn-block mt-5">Créer</button>
                </form>
                <!--links -->
                <p class="mt-3 mb-0 text-center">
                    <a href="{% url 'authentication:login'%}" class="text-center">Déja un compte? Connectez vous</a>
                </p>
                <!--./links -->
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}

authentication/templates/authentication/delete_custom_user.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="../../index2.html"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Supprimer le compte
                    <span class="font-weight-bold"> "{{user}}" </span>
                    ?
                </p>

                <form id="delete_custom_user_form" action="{% url 'authentication:delete_custom_user'%}" method="post" novalidate>
                </form>
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'information:home'%}" role="button">
                            <button type="button" class="btn btn-secondary btn-block mt-3">
                                Annuler
                            </button>
                        </a>
                    </div>
                    <div class="col-6">
                        <button type="submit" form="delete_custom_user_form" class="btn btn-danger btn-block mt-3">
                            Supprimer
                        </button>
                    </div>
                </div>
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
{% if messages %}
    {% for message in messages %}
    <div class="card-body bg-transparent">
        {% if message.level_tag == 'error' %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-ban"></i> {{ message }}.
    
        </div>
        {% endif %}
        {% if message.level_tag == 'warning' %}
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-ban"></i> {{ message }}.
        </div>
        {% endif %}
        {% if message.level_tag == 'success' %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-check"></i> {{ message }}.
        </div>
        {% endif %}
    </div>
    
    {% endfor %}
{% endif %}
<div class=" login-page">
<div class="login-box ">
    <div class="login-logo">
        <a href="{% url 'information:home'%}"><b>sel-</b>E</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Connectez-vous à votre compte</p>

                <form id="login_form" action="{% url 'authentication:login'%}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group mb-3">
                        {{ field.label }}
                        {{ field }}
                        {% for error in field.errors %}
                            {% if error %}
                                <p class="text-danger"> {{ error }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <button type="submit" id="login_button" class="btn btn-primary btn-block mt-5">Se connecter</button>
                </form>

            <!-- /.social-auth-links -->

            <p class="mt-3 mb-0 text-center">
                <a href="{% url 'authentication:create_custom_user'%}" class="text-center">Pas de compte? Créer un compte</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
</div>
<!-- /.login-box -->
<!-- /.content -->
{% endblock %}

authentication/templates/authentication/read_custom_user.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Utilisateur - <span class="text-primary font-weight-bold font-italic">
                        {{user.user_name}}</span></h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fas fa-user-check mr-1"></i>Détail</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="card-body">
                        <p class="card-text">Email:</br>
                        <span class="card-text text-secondary">{{user.email}}</span></p>
                        <p class="card-text">Nom utilisateur.rice:</br>
                            <span class="card-text text-secondary">{{user.user_name}}</span>
                        </p>
                        <p class="card-text">Code postal:</br>
                            <span class="card-text text-secondary">{{user.collectivity.postal_code}}</span>
                        </p>
                        <p class="card-text">Ville:</br>
                            <span class="card-text text-secondary">{{user.collectivity.name}}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer bg-white clearfix">
            <div class="row mb-2">
                <div class="col-sm-3 mt-4"></div>
                <div class="col-sm-6 mt-4"></div>
                <div class="col-sm-3 mt-4">
                    <a href= "{{ request.META.HTTP_REFERER }}"  role="button">
                        <button type="button" class="text-secondary btn btn-block btn-light border border-secondary btn-sm">Retour</button>
                    </a>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>

</section>
<!-- /.content -->
{% endblock %}

authentication/templates/authentication/update_custom_user.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="../../index2.html"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Modifier mon compte</p>
                <form id="update_custom_user_form" action="{% url 'authentication:update_custom_user'%}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group mb-3">
                            {{ field.label }}
                            {{ field }}
                            {% for error in field.errors %}
                                {% if error %}
                                    <p class="text-danger"> {{ error }}</p>
                                {% endif %}
                            {% endfor %}
                            {% if field == form.postal_code or field == form.collectivity%}
                                {% if messages %}
                                    {% for message in messages %}
                                        <p class="text-danger"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endfor %}

                </form>
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'information:home'%}" role="button">
                            <button type="button" class="btn btn-secondary btn-block mt-5">
                                Annuler
                            </button>
                        </a>
                    </div>
                    <div class="col-6">
                        <button type="submit" form="update_custom_user_form" class="btn btn-success btn-block mt-5">
                            Modifier
                        </button>
                    </div>
                </div>
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}