authentication/urls.py
# pylint: disable=C0103
"""Authentication urls module.
"""
from django.urls import path

from authentication.views.delete_custom_user_view import DeleteCustomUserView
from authentication.views.login_view import LoginView
from authentication.views.logout_view import LogoutView
from authentication.views.create_custom_user_view import CreateCustomUserView
from authentication.views.update_custom_user_view import UpdateCustomUserView
from authentication.views.read_custom_user_view import ReadCustomUserView

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'create_custom_user/',
        CreateCustomUserView.as_view(),
        name='create_custom_user'
    ),
    path(
        'delete_custom_user/',
        DeleteCustomUserView.as_view(),
        name='delete_custom_user'
    ),
    path(
        'update_custom_user/',
        UpdateCustomUserView.as_view(),
        name='update_custom_user'
    ),
    path(
        'read_custom_user/',
        ReadCustomUserView.as_view(),
        name='read_custom_user'
    ),
]

chat/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from chat.views.collectivity_discussions_view import (
    CollectivityDiscussionsView
)
from chat.views.create_comment_view import CreateCommentView
from chat.views.create_discussion_view import CreateDiscussionView
from chat.views.read_discussion_view import ReadDiscussionView


app_name = 'chat'

urlpatterns = [
    path(
        'collectivity_discussions/',
        CollectivityDiscussionsView.as_view(),
        name='collectivity_discussions'
    ),
    path(
        'create_comment/<int:id_discussion>/',
        CreateCommentView.as_view(),
        name='create_comment'
    ),
    path(
        'create_discussion/',
        CreateDiscussionView.as_view(),
        name='create_discussion'
    ),
    path(
        'read_discussion/<int:id_discussion>/',
        ReadDiscussionView.as_view(),
        name='read_discussion'
    )
]

information/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from information.views.about_view import AboutView
from information.views.contact_view import ContactView
from information.views.collectivity_dashboard_view import (
    CollectivityDashboardView
)
from information.views.faq_view import FaqView
from information.views.legal_view import LegalView
from information.views.home_view import HomeView

app_name = 'information'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('faq/', FaqView.as_view(), name='faq'),
    path(
        'information/collectivity_dashboard/',
        CollectivityDashboardView.as_view(),
        name='collectivity_dashboard'
    ),
    path('legal/', LegalView.as_view(), name='legal'),
]

proposition/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from proposition.views.collectivity_propositions_view import (
    CollectivityPropositionsView
)
from proposition.views.create_proposition_view import CreatePropositionView
from proposition.views.delete_proposition_view import DeletePropositionView
from proposition.views.read_proposition_view import ReadPropositionView
from proposition.views.update_proposition_view import UpdatePropositionView

app_name = 'proposition'

urlpatterns = [
    path(
        'collectivity_propositions/',
        CollectivityPropositionsView.as_view(),
        name='collectivity_propositions'
    ),
    path(
        'create_proposition/',
        CreatePropositionView.as_view(),
        name='create_proposition'
    ),
    path(
        'delete_proposition/<int:id_proposition>/',
        DeletePropositionView.as_view(),
        name='delete_proposition'
    ),
    path(
        'read_proposition/<int:id_proposition>/',
        ReadPropositionView.as_view(),
        name='read_proposition'
    ),
    path(
        'update_proposition/<int:id_proposition>/',
        UpdatePropositionView.as_view(),
        name='update_proposition'
    ),
]

information/models/question.py
"""Question model module.
"""
from django.db import models


class Question(models.Model):
    """Question model class.
    """

    question = models.CharField(max_length=256, unique=False)
    answer = models.TextField(max_length=1000)

information/views/about_view.py
"""AboutView module.
"""
from django.shortcuts import render
from django.views import View


class AboutView(View):
    """About view class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'information/about.html'
        self.context = {}

    def get(self, request):
        """AboutView method on client get request.
        """
        return render(request, self.view_template, self.context)

information/views/collectivity_dashboard_view.py
"""CollectivityDashboardView module.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from information.management.engine.manager import Manager


class CollectivityDashboardView(LoginRequiredMixin, View):
    """CollectivityDashboardView class.
    """

    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()
        self.view_template = 'information/collectivity_dashboard.html'
        self.context = {
            'custom_user_pag_obj': None,
            'custom_users_p_counts': None,
            'proposition_pag_obj': None,
            'discussion_pag_obj': None,
            'voting_pag_obj': None,
            'collectivity_p_counts': None,
            'collectivity_cu_counts': None,
            'collectivity_d_counts': None,
            'collectivity_v_counts': None
        }

    def get(self, request):
        """CollectivityDashboardView method on client get request.
        """
        self.context = self.manager.set_collectivity_dashboard_context(
            request, self.context
        )
        return render(request, self.view_template, self.context)

information/views/contact_view.py
"""ContactView module.
"""
from django.views import View
from django.shortcuts import render


class ContactView(View):
    """Contact view class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'information/contact.html'
        self.context = {}

    def get(self, request):
        """ContactView method on client get request.
        """
        return render(request, self.view_template, self.context)

information/views/faq_view.py
# pylint: disable=E1101
"""FaqView module.
"""
from django.shortcuts import render
from django.views import View

from information.models.question import Question


class FaqView(View):
    """FaqView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'information/faq.html'
        self.context = {'questions': None}

    def get(self, request):
        """FaqView method on client get request.
        """
        self.context['questions'] = Question.objects.all().order_by('id')
        return render(request, self.view_template, self.context)

information/views/home_view.py
"""HomeView module.
"""
from django.shortcuts import render
from django.views import View

from information.management.engine.manager import Manager


class HomeView(View):
    """HomeView class.
    """
    def __init__(self):
        super().__init__()
        self.manager = Manager()
        self.view_template = 'information/home.html'
        self.context = {
            'mapbox_url': None,
            'vector_layer': None,
            'stats_data': None,
            'all_p_counts': None,
            'all_cu_counts': None,
            'all_co_counts': None,
            'all_v_counts': None,
            'propositions': None
        }

    def get(self, request):
        """HomeView method on client get request.
        """
        self.context = self.manager.set_home_context(self.context)
        return render(request, self.view_template, self.context)

information/views/legal_view.py
"""LegalView module.
"""
from django.shortcuts import render
from django.views import View


class LegalView(View):
    """LegalView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'information/legal.html'
        self.context = {}

    def get(self, request):
        """LegalView method on client get request.
        """
        return render(request, self.view_template, self.context)

information/templates/information/contact.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Contact</h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <!-- right col -->
            <!-- one col (We are only adding the ID to make the widgets sortable)-->
            <section class="col">

                <!-- Last poposals cards -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-info mr-1"></i>
                            Contact
                        </h3>
                    </div>
                    <!-- Table . 2nd card-body-->
                    <div class="card-body text-center">
                        <h5><i class="far fa-envelope mr-2"></i></h5>
                        <p>
                            
                            sel-e@outlook.fr
                        </p>
                        
                    </div>
                </div>
                <!-- /.card -->
            </section>

        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

information/templates/information/faq.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">FAQ</h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <!-- right col -->
            <!-- one col (We are only adding the ID to make the widgets sortable)-->
            <section class="col">

                <!-- Last poposals cards -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-info mr-1"></i>
                            FAQ
                        </h3>
                    </div>
                    <div class="card-body mt-3 mb-2">
                        <!-- Form -->
                    </div>
                    <!-- Table . 2nd card-body-->
                    <div class="card-body">
                        {% for question in questions%}
                        <h5><span class="font-weight-bold">#{{question.id}}</span>
                        {{question.question}}</h5>
                        <p class="card-text">
                            {{question.answer}}
                        </p>
                        {% endfor %}

                    </div>
                    <!-- /.card-footer-->
                </div>
                <!-- /.card -->
            </section>

        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

information/templates/information/home.html
{% extends 'information/base.html' %}
{% block content %}
  {% load static %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        {% include 'information/messages.html' %}
        <div class="row">
          <div class="col-sm-6">
            <div class="row mb-2">
              <div class="col-12">
                <h1 class="m-0">sel-e</h1>
                <h5 class="m-0">système d'échange local électronique</h5>
              </div><!-- /.col -->
            </div><!-- /.row -->
            <div class="row mb-2">
              <div class="col-12 col-md-9 col-lg-8 col-xl-6">
                <a href="{% url 'authentication:login'%}">
                  <button type="button" id="go_to_login_button" class="mt-3 btn btn-block btn-outline-primary">Connexion</button>
                </a>
              </div><!-- /.col -->
            </div>
          </div>
          <div class="col-sm-6">
              <div class="w-100 mt-5 mb-5 text-center ">
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="10000">
                  <div class="carousel-inner text-secondary">
                    <div class="carousel-item active">
                      <h3 class="d-block w-100 font-italic font-weight-bold">
                        <span class="h5"><i class="fas fa-quote-left text-secondary"></i></span>
                        Echangez dans un réseau local
                        <span class="h5"><i class="fas fa-quote-right text-secondary"></i></span>
                      </h3>
                    </div>
                    <div class="carousel-item">
                      <h3 class="d-block w-100 font-italic font-weight-bold">
                        <span class="h5"><i class="fas fa-quote-left text-secondary"></i></span>
                        Mettez vos compétences à disposition
                        <span class="h5"><i class="fas fa-quote-right text-secondary"></i></span>
                      </h3>
                    </div>
                    <div class="carousel-item">
                      <h3 class="d-block w-100 font-italic font-weight-bold">
                        <span class="h5"><i class="fas fa-quote-left text-secondary"></i></span>
                        Prenez des décisions collectives
                        <span class="h5"><i class="fas fa-quote-right text-secondary"></i></span>
                      </h3>
                    </div>
                    <div class="carousel-item">
                      <h3 class="d-block w-100 font-italic font-weight-bold">
                        <span class="h5"><i class="fas fa-quote-left text-secondary"></i></span>
                        Faites des demandes individuelles
                        <span class="h5"><i class="fas fa-quote-right text-secondary"></i></span>
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
          </div>  
        </div>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-white">
              <div class="inner">
                <h3>{{all_p_counts}}</h3>

                <p>Nombre de propositions</p>
              </div>
              <div class="icon">
                <i class="fas fa-tags"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-white">
              <div class="inner">
                <h3>{{all_cu_counts}}</h3>

                <p>Nombre de membres</p>
              </div>
              <div class="icon">
                <i class="fas fa-user"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-white">
              <div class="inner">
                <h3>{{all_co_counts}}</h3>

                <p>Nombre de groupes</p>
              </div>
              <div class="icon">
                <i class="fas fa-users"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-white">
              <div class="inner">
                <h3>{{all_v_counts}}</h3>

                <p>Nombre de votations</p>
              </div>
              <div class="icon">
                <i class="fas fa-vote-yea"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->

        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-6">
            <div class="card " style="height: 410px;">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-chart-bar mr-1"></i>
                    Statistiques
                </h3>
            
              </div>
              <div class="card-body">
                <div class="chart">
                  <canvas id="lineChart" style="min-height: 250px; height: 330px; max-height: 330px; max-width: 100%;" tp-json="{{ stats_data }}"></canvas>
                </div>
              </div>
              <!-- /.card-body -->
            </div>



          </section>
          <!-- /.Left col -->
          <!-- right col (We are only adding the ID to make the widgets sortable)-->
          <section class="col-lg-6">

            <!-- Map card -->
            <div class="card" style="height: 410px;">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-map mr-1"></i>
                  Groupes locaux actifs
                </h3>
              </div>
              <div class="card-body">
                <div id="map" style="height: 325px; width: 100%;" data-json="{{ mapbox_url }}" data-geojson="{{ vector_layer }}"></div>
              </div>
              <!-- /.card-body-->
            </div>
            <!-- /.card -->
          </section>
          
          <!-- right col -->
          <!-- one col (We are only adding the ID to make the widgets sortable)-->

        </div>
        <div class="row">
          <!-- one col (We are only adding the ID to make the widgets sortable)-->
          <section class="col">
          
            <!-- Last poposals cards -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-tags mr-1"></i>
                  Dernières propositions
                </h3>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for proposition in propositions%}
                  <div class="col-lg-3 col-6">
                    <div class="card ">
                      <!-- <div class="card-header text-center bg-primary">
                        Demande
                      </div> -->
                        <div class="card-body">
                          <div class="text-right">
                            <h6><span class="text-dark font-weight-bold">
                                {{proposition.proposition_kind}}
                              </span>
                            </h6>
                          </div>
                          <div class="col-12  text-truncate">
                          <h5 class="text-left">{{proposition.name}} </h5>
                          <p class="">
                            Domaine:
                            <span class="text-secondary">
                              {{proposition.proposition_domain}}
                            </span></br>
                            Catégorie:
                            <span class="text-secondary">
                              {{proposition.proposition_category}}
                            </span></br>
                            Durée de travail:
                            <span class="text-secondary">
                              {{proposition.duration}} minutes
                            </span></br>
                            Description:
                            <span class="text-secondary">
                              {{proposition.description}}
                            </span></br>
                            Portée:
                            <span class="text-secondary">
                              {{proposition.proposition_creator_type}}
                            </span></br>
                            Groupe local:
                            <span class="text-secondary">
                              {{proposition.proposition_creator.collectivity}}
                            </span></br>
                          </p>
                          {% if user.collectivity == proposition.proposition_creator.collectivity%}
                            <div class="text-center">
                              <a href="{% url 'proposition:read_proposition' id_proposition=proposition.id %}" class="card-link text-center">Plus d'infos <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                          {% endif %}
                        </div>
                      </div>
                    </div><!-- /.card -->
                  </div>
                  {% endfor%}
                
                </div>
              </div>
              <!-- /.card-body-->
          
            </div>
            <!-- /.card -->
          </section>



        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

information/templates/information/home_prod.html
{% extends 'information/base.html' %}

{% block content %}
{% load static %}
    <div class="bg-dark text-center" style="height: 1100px;">
        <div class="container-fluid">
        <h1 class="display-2 text-primary pt-5">sel-e</h1>
        <p class="display-6 text-secondary">système d'échange local électronique</p>
        <img src="{% static 'information/images/sele_blue.jpg' %}" id="" width="400" alt="under construction">
        <h1 class="lead text-secondary mt-5">En construction. En ligne à T2 2022.</h1>
        </div>
    </div>

{% endblock %}

information/templates/information/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="card-body">
        {% if message.level_tag == 'error' %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-ban"></i> {{ message }}

        </div>
        {% endif %}
        {% if message.level_tag == 'warning' %}
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-exclamation-triangle"></i> {{ message }}
        </div>
        {% endif %}
        {% if message.level_tag == 'success' %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fas fa-check"></i> {{ message }}
        </div>
        {% endif %}
    </div>

    {% endfor %}
{% endif %}

information/templates/information/pagination.html
<div class="row align-items-end text-center">
    <div class="col">
        <ul class="pagination pagination-sm m-0 float-right">
            {% if page_objects.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_objects.previous_page_number }}">&laquo;</a></li>
            {% endif %}
            {% for i in page_objects.paginator.page_range %}
                {% if page_objects.number == i %}
                    <li class="page-item active"><a class="page-link" href=?page="{{ i }}">{{i}}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_objects.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_objects.next_page_number }}">&raquo;</a></li> 
            {% endif %}
        </ul>
    </div>
</div>